service: s3-sitter
app: S3Sitter

provider:
  name: aws
  runtime: python3.7
  environment:
    CheckFreqInMins: 10
    FunctionName: S3Nanny

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "events:PutEvents"
        - "cloudwatch:PutMetricData"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: ${file(./${env:FunctionName}_resources.yml)}

package:
  individually: true
  exclude:
    - ./**
  include:
    - s3_sitter/__init__.py
    - s3_sitter_lambda.py

functions:
  s3_sitter_handler:
    handler: s3_sitter_lambda.handler
    name: ${env:FunctionName}
    events:
      - schedule:
          rate: rate(${env:CheckFreqInMins} minutes)
          enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
